# Create a program that will play the “cows and bulls” game with the user. The game works like this:
#
# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the user
# guessed correctly in the correct place, they have a “cow”. For every digit the user guessed
# correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many
# “cows” and “bulls” they have. Once the user guesses the correct number, the game is over.
# Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.
# 
# Say the number generated by the computer is 1038. An example interaction could look like this:
#
#   Welcome to the Cows and Bulls Game!
#   Enter a number:
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull
#   ...
#
# Until the user guesses the number.


def cow_and_bulls():
    import random
    random_number = [random.randint(0,9) for i in range(4)]
    # print(random_number)
    counter = 1

    def get_number(text):
        users_number = input(text)
        while users_number.isnumeric() == False and len(users_number) != 4:
            users_number = input("Format musi być właściwy - podaj raz jeszcze! ")

        return [int(i) for i in users_number]

    users_number = get_number("Podaj 4 cyfrowy numer (może być np '0001'): ")

    while random_number != users_number:
        cows = 0
        bulls = 0

        for i in range(0, 4):
            if users_number[i] == random_number[i]:
                cows += 1
            elif users_number[i] in random_number:
                bulls += 1
        counter += 1

        print("To nie ten numer! Znalazłeś ", cows, " krów i ", bulls, " byków!")

        users_number = get_number("Podaj nowy numer")

    print("Brawo! Zgadłeś za ", counter, " razem!")


if __name__ == "__main__":
    cow_and_bulls()